# -*- coding: utf-8 -*-
"""SDP Manager Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AluvUznyUdbkmgx6F-SYtlgdFDt1qrBV

---
## **1️⃣  Loading the libraries**
"""

import pandas as pd

"""## **2️⃣ Prepare Your Data**


"""

# Read data from a file
df = pd.read_csv('SDP Manager Performance vs Direct Reports.csv')

# Print the DataFrame
df.head()

df.shape

# Converting multiple string columns to numerical values
df[['No. Direct Reports', 'H1 Performance %']] = df[['No. Direct Reports', 'H1 Performance %']].apply(pd.to_numeric, errors='coerce')

# Check that it worked
df.info()

# Identify rows with null values
bad_rows = df[df['No. Direct Reports'].isna()]
bad_rows['No. Direct Reports']

# Drop null values
df = df.dropna(subset=['No. Direct Reports'])

# Convert 'No. Direct Reports' to an int
df['No. Direct Reports'] = pd.to_numeric(df['No. Direct Reports'], errors='coerce').astype('int64')

# Specify that I intend to modify the real DataFrame after above warning
df.loc[:, 'No. Direct Reports'] = (
    pd.to_numeric(df['No. Direct Reports'], errors='coerce').astype('int64')
)

"""---
## **3️⃣ Visualise the data**

**Visualise the Scatter plot**
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.scatterplot(x=df["No. Direct Reports"], y=df["H1 Performance %"])
plt.xlabel("No. Direct Reports")
plt.ylabel("H1 Performance %")
plt.title("H1 Performance % vs No. Direct Reports")
plt.grid(True)
plt.show()

"""**Note**

Always look for a linear relationship. If you don't see it, then most probably the predictor is not a good one.

**Visualise the data and the Regression Line**
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
# Create the scatter plot with regression line
sns.regplot(x='No. Direct Reports', y='H1 Performance %', data=df, line_kws={"color": "red"} )

plt.title("H1 Performance % by No. Direct Reports")
plt.xlabel('No. Direct Reports')
plt.ylabel('H1 Performance %')

# Display the plot
plt.grid(True)
plt.show()

"""**Pearson Correlation Coefficient** (correlation_coefficient) ranges between -1 and 1.

It represents the strength and direction of the linear relationship between two variables.

A positive coefficient indicates a positive linear relationship (as one variable increases, the other tends to increase), while a negative coefficient indicates a negative linear relationship (as one variable increases, the other tends to decrease).

A coefficient of 0 suggests no linear relationship.
"""

# Find correlation
df[['No. Direct Reports', 'H1 Performance %']].corr()

# Heatmap of correlation
sns.heatmap(df[['No. Direct Reports', 'H1 Performance %']].corr(), annot=True)
plt.show()

"""---
##**4️⃣ Fit the LR Model**
"""

# use `scikit-learn`:

from sklearn.linear_model import LinearRegression
import numpy as np

# Reshape X for sklearn
X = df[["No. Direct Reports"]]
y = df["H1 Performance %"]

model = LinearRegression()
model.fit(X, y)

"""---

## **5️⃣ Get the Equation of the Line**

"""

slope = model.coef_[0]
intercept = model.intercept_

print(f"y = {slope:.2f}x + {intercept:.2f}")

"""---

## **6️⃣ Make one prediction**

Now that you've trained your model, you can use it to predict the target based on the predictor.
"""

# Create a DataFrame with the new no. direct reports
new_data = pd.DataFrame({"No. Direct Reports": [1]})

# Predict the target % using the trained model
prediction = model.predict(new_data)  # This gives us a list with one predicted value

# Print the raw prediction result
print(prediction)

# Print the predicted % in a readable format
print(f"Predicted target performance based on no. direct reports: {prediction[0]:,.2f}%")

"""# **Evaluating the SRL Model**

Now that we've built a linear regression model and made predictions, it’s important to answer the question:

>**"How good is the model?"**

In other words — how well does the model’s predicted values match the actual data?

## **Why evaluate?**
Evaluation helps us:

- Understand if our model is reliable
- Detect underfitting or overfitting
- Compare different models or features

## **What are we evaluating?**

We're comparing:
- Actual values (from our dataset)
- Predicted values (from the model)

## **Key evaluation metrics for Linear Regression**

Here are the most common ways to evaluate a linear regression model:

| Metric                                   | Description                                                           | Evaluation                  |
|------------------------------------------|-----------------------------------------------------------------------|-----------------------------|
| **Mean Absolute Error (MAE)**            | Average of all absolute errors (easy to interpret)                    | The smaller the better      |
| **Root Mean Squared Error (RMSE)**       | Square root of MSE — brings error back to original units              | The smaller the better      |
| **R² Score (Coefficient of Determination)** | Measures how well the line fits the data (ranges from 0 to 1)         | The closer to 1, the better |

## **Let's evaluate our model**

Let's use the **training data** (`X` and `y`) to check how well the model fits it.

---
## **1️⃣  Loading the libraries**
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

"""---
## **2️⃣ Predict on training data**
"""

# Get predictions on the training data
y_pred = model.predict(X)

"""---
## **3️⃣ Calculate the metrics**
"""

# Calculate evaluation metrics
mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))
r2 = r2_score(y, y_pred)

"""---

## **4️⃣ Display the results**
"""

# Display the results
print(f"Mean Absolute Error (MAE): {mae:,.2f}%")
print(f"Root Mean Squared Error (RMSE): {rmse:,.2f}%")
print(f"R² Score: {r2:.4f}")

"""##  **6️⃣ Visualising actual vs predicted**


We can also **plot actual vs predicted** to see how well they line up. This step is optional, but helpful.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,6))

sns.scatterplot(x=y, y=y_pred)
plt.plot([min(y), max(y)], [min(y), max(y)], color='red', linestyle='--')

plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Actual vs Predicted values")
plt.grid(True)
plt.show()

"""If your model is good, points will be close to the **diagonal line** (y = x).

## **Decide if the model is "Good"?**

- **Low error values** (MAE, RMSE)
- **High R² score** (close to 1)
- **Predictions follow the trend** shown in your data
"""

# Calculate average H1 performance % by office
df.groupby('Office')['H1 Performance %'].mean().sort_values(ascending=False)

# See how consistent each office is
df.groupby('Office')['H1 Performance %'].agg(['mean', 'median', 'std', 'count'])

# Visualise differences between offices
plt.figure(figsize=(10,6))
sns.boxplot(x='Office', y='H1 Performance %', data=df)
plt.title("H1 Performance % Distribution by Office")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# Bar chart of average values
plt.figure(figsize=(10,5))
sns.barplot(x='Office', y='H1 Performance %', data=df, estimator='mean')
plt.title("Average H1 Performance % by Office")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

import scipy.stats as stats

# Create a list of performance arrays, one for each office
groups = [group["H1 Performance %"].values for name, group in df.groupby("Office")]

# One-way ANOVA
stats.f_oneway(*groups)